// Dog Years Project 

// Value of my age  
var myAge = 27; 

// Value of earlyYears | will change 
var earlyYears = 2;

// Multiplication of earlyYears | new value = 21 
earlyYears *= 10.5; 

// Subtracted myAge by 2 | laterYears = 25 
myAge -= 2; 

var laterYears = 25;

// Multiplication of laterYears by 4 | laterYears = 100 
laterYears *= 4; 

// Added earlyYears + laterYears *checked by console.log*
earlyYears += laterYears 
var myAgeInDogYears = 121

// Value of myName
const myName = 'GARRETT'.toLowerCase(); 

console.log(`My name is ${myName}. I am ${myAge} years old in human years which is ${myAgeInDogYears} in dog years.`); 
